name: Nexus
main: net.SimplyCrafted.Nexus.Nexus
version: 0.7
author: Brian Ronald
commands:
    nexus:
        description: Creates and activates a Nexus pad
        usage: |
            Town mayors only - build a Nexus pad in town:
             /nexus build
            Server staff only:
             /nexus build <town> town
             /nexus build <town> hall
             /nexus destroy <town>
             /nexus list
             /nexus info <town>
             /nexus override
             /nexus warp
             /nexus reload
softdepend:
    - Towny
permissions:
    Nexus.*:
        description: Access to all Nexus commands
        children:
            Nexus.warp: true
            Nexus.create: true
            Nexus.request: true
            Nexus.admin: true
    Nexus.create:
        description: Can create and activate Nexus pads
        default: op
    Nexus.request:
        description: Can request a new Nexus pad
        default: op
    Nexus.admin:
        description: Can reload the plugin
        default: op
    Nexus.warp:
        description: Can teleport to a Nexus pad
        default: op
