chatcolor: GOLD
padmaterial: LAPIS_BLOCK
platematerial: STONE_PLATE
cooldown: 3
triggerradius: 2
townyfeenew: 5000
townyfeemove: 1000

messages:
    # If a message is the word "empty" (unquoted) it will not be displayed.
    # Using a blank entry will revert it to the default.
    nopermtobuild:    You don't have permission to build a Nexus pad here
    nocreativebuild:  You cannot build a Nexus pad in creative mode
    nameproblem:      A Nexus with the same name as your town exists outside your town. Contact a moderator for assistance.
    nopermtodestroy:  You do not have permission to destroy a Nexus
    nopermtooverride: You do not have permission to override a Nexus
    nopermtolist:     You do not have permission to list all Nexus
    nopermtoview:     You do not have permission to view Nexus details
    nopermtoreload:   You do not have permission to reload the plugin
    nopermtorename:   You do not have permission to rename a Nexus
    nopermtowarp:     You do not have permission to teleport to a Nexus
    nosuchnexus:      There is no Nexus of that name
    renaming:         Renaming Nexus from %s to %s
    forcing:          Forcing activation of %s Nexus
    nopadhere:        This is not a Nexus pad location
    disabled:         Traveling by %s Nexus pad disabled; pressure plate is missing at other end
    traveling:        Traveled using the %s Nexus pad
    aborted:          Nexus transport failed; you left the pad
    takefeemove:      Moving a Nexus pad costs %d
    takefeenew:       Building a new Nexus pad costs %d
    paidfromtownbank: This fee has been paid from the town's bank
    filemodreqnow:    Please file a modreq asking to have the other end built
    towncannotafford: There isn't enough in the town's bank to pay this
    buildhelp:        You must specify a town name (case sensitive) and either "town" or "hall"
    buildingtown:     Building town pad for %s
    buildinghall:     Building hall pad for %s
    createdinworld:   Nexus created for %s; distance is %.1fm
    createdexworld:   Nexus created for %s; Nexus is trans-world
    destroying:       Destroying both pads for %s
    specifyname:      You must specify a name
    reloading:        Reloading config from disk!

allowedblocks:
  - STONE
  - GRASS
  - DIRT
  - COBBLESTONE
  - WOOD
  - BEDROCK
  - SAND
  - GRAVEL
  - GOLD_ORE
  - IRON_ORE
  - COAL_ORE
  - LOG
  - SPONGE
  - LAPIS_ORE
  - LAPIS_BLOCK
  - SANDSTONE
  - NOTE_BLOCK
  - WOOL
  - GOLD_BLOCK
  - IRON_BLOCK
  - BRICK
  - BOOKSHELF
  - MOSSY_COBBLESTONE
  - OBSIDIAN
  - DIAMOND_ORE
  - DIAMOND_BLOCK
  - WORKBENCH
  - FURNACE
  - BURNING_FURNACE
  - REDSTONE_ORE
  - GLOWING_REDSTONE_ORE
  - SNOW_BLOCK
  - CLAY
  - JUKEBOX
  - PUMPKIN
  - NETHERRACK
  - JACK_O_LANTERN
  - SMOOTH_BRICK
  - HUGE_MUSHROOM_1
  - HUGE_MUSHROOM_2
  - MELON_BLOCK
  - MYCEL
  - NETHER_BRICK
  - ENDER_STONE
  - REDSTONE_LAMP_OFF
  - REDSTONE_LAMP_ON
  - EMERALD_ORE
  - EMERALD_BLOCK
  - COMMAND
  - REDSTONE_BLOCK
  - QUARTZ_ORE
  - QUARTZ_BLOCK
  - STAINED_CLAY
  - HAY_BLOCK
  - HARD_CLAY
  - COAL_BLOCK