chatcolor: GOLD
padmaterial: LAPIS_BLOCK
cooldown: 3
allowedblocks:
  - STONE
  - GRASS
  - DIRT
  - COBBLESTONE
  - WOOD
  - BEDROCK
  - SAND
  - GRAVEL
  - GOLD_ORE
  - IRON_ORE
  - COAL_ORE
  - LOG
  - SPONGE
  - LAPIS_ORE
  - LAPIS_BLOCK
  - SANDSTONE
  - NOTE_BLOCK
  - WOOL
  - GOLD_BLOCK
  - IRON_BLOCK
  - BRICK
  - BOOKSHELF
  - MOSSY_COBBLESTONE
  - OBSIDIAN
  - DIAMOND_ORE
  - DIAMOND_BLOCK
  - WORKBENCH
  - FURNACE
  - BURNING_FURNACE
  - REDSTONE_ORE
  - GLOWING_REDSTONE_ORE
  - SNOW_BLOCK
  - CLAY
  - JUKEBOX
  - PUMPKIN
  - NETHERRACK
  - JACK_O_LANTERN
  - SMOOTH_BRICK
  - HUGE_MUSHROOM_1
  - HUGE_MUSHROOM_2
  - MELON_BLOCK
  - MYCEL
  - NETHER_BRICK
  - ENDER_STONE
  - REDSTONE_LAMP_OFF
  - REDSTONE_LAMP_ON
  - EMERALD_ORE
  - EMERALD_BLOCK
  - COMMAND
  - REDSTONE_BLOCK
  - QUARTZ_ORE
  - QUARTZ_BLOCK
  - STAINED_CLAY
  - HAY_BLOCK
  - HARD_CLAY
  - COAL_BLOCK